version: "3.9"
services:
  web:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/frontend/pages
      - ./utils:/frontend/utils
      - ./components:/frontend/components
